apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 9000           # 对外暴露的端口（K8s Service Port）
      nodePort: 30090     # 显式暴露为宿主机 30090
  type: NodePort