apiVersion: v1
kind: Service
metadata:
  name: house-client-service
spec:
  selector:
    app: house-client-service
  ports:
    - port: 80          # 集群内访问端口
      targetPort: 8081  # Spring Boot 监听端口
  type: ClusterIP       # 内部服务访问，API Gateway 可通过服务名访问
