server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:clientdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: house-client-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 使用 IP 注册（推荐）
    ip-address: 127.0.0.1    # 明确指定为 localhost



