spring:
  application:
    name: house-client-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true


logging:
  level:
    org.springframework.security: DEBUG
