server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:k8s-clientdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
