spring:
  application:
    name: house-client-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

profiles:
  active: dev
